import { createHash, randomUUID } from 'node:crypto';
import type { Db } from '../lib/db.js'; import type { Actor } from '../lib/auth.js'; import { AppError } from '../lib/errors.js'; import { audit } from '../lib/audit.js'; import { fromPaise, multiply, toPaise } from '../lib/money.js';

export type SaleInput = { customerId?: string; locationId: string; items: { variantId: string; quantity: number; discount?: string }[]; payments: { amount: string; method: 'CASH'|'UPI'|'CARD'|'BANK_TRANSFER'|'OTHER'; reference?: string }[] };
type Reply = { invoiceId: string; invoiceNumber: string; grandTotal: string; amountPaid: string; amountDue: string; paymentStatus: string };
const requestHash = (input: SaleInput) => createHash('sha256').update(JSON.stringify(input)).digest('hex');
const tax = (net: bigint, rate: string) => { const basisPoints = toPaise(rate); return (net * basisPoints + 5000n) / 10000n; };

export async function postSale(db: Db, actor: Actor, input: SaleInput, idempotencyKey: string, context: { ip: string | null; requestId: string }): Promise<Reply> {
  const bodyHash = requestHash(input);
  const claimed = await db.query(`INSERT INTO idempotency_keys(key,user_id,request_hash) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING key`, [idempotencyKey, actor.id, bodyHash]);
  if (!claimed.rowCount) {
    const prior = await db.query('SELECT user_id,request_hash,status_code,response_body FROM idempotency_keys WHERE key=$1 FOR UPDATE', [idempotencyKey]); const record = prior.rows[0];
    if (record.user_id !== actor.id || record.request_hash !== bodyHash) throw new AppError(409, 'Idempotency key was already used with a different request.', 'IDEMPOTENCY_CONFLICT');
    if (record.status_code && record.response_body) return record.response_body as Reply;
    throw new AppError(409, 'A matching request is still being processed. Retry shortly.', 'REQUEST_IN_PROGRESS');
  }
  if (input.customerId) { const customer = await db.query('SELECT id FROM customers WHERE id=$1 AND deleted_at IS NULL', [input.customerId]); if (!customer.rowCount) throw new AppError(404, 'Customer was not found.', 'CUSTOMER_NOT_FOUND'); }
  const ids = input.items.map(item => item.variantId); const products = await db.query(`SELECT v.id,v.sku,v.selling_price,p.tax_rate,p.product_name AS name,v.variant,v.color FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id=ANY($1::uuid[]) AND v.active AND p.is_active FOR UPDATE`, [ids]);
  if (products.rowCount !== ids.length || new Set(ids).size !== ids.length) throw new AppError(422, 'One or more products are unavailable.', 'PRODUCT_UNAVAILABLE');
  await db.query(`INSERT INTO inventory_balances(variant_id,location_id,quantity) SELECT unnest($1::uuid[]),$2,0 ON CONFLICT DO NOTHING`, [ids,input.locationId]);
  const balances = await db.query(`SELECT variant_id,quantity FROM inventory_balances WHERE location_id=$1 AND variant_id=ANY($2::uuid[]) FOR UPDATE`, [input.locationId,ids]); const quantities = new Map(balances.rows.map(row => [row.variant_id, row.quantity as number]));
  const byId = new Map(products.rows.map(row => [row.id, row])); let subtotal = 0n, discountTotal = 0n, taxTotal = 0n;
  const lines = input.items.map(item => { const product = byId.get(item.variantId)!; const price = toPaise(product.selling_price); const discount = toPaise(item.discount ?? '0.00'); const gross = multiply(price,item.quantity); if (discount > gross) throw new AppError(422, `Discount exceeds price for ${product.sku}.`, 'INVALID_DISCOUNT'); const net = gross-discount; const lineTax = tax(net,product.tax_rate); if ((quantities.get(item.variantId) ?? 0) < item.quantity) throw new AppError(409, `${product.sku} has insufficient stock.`, 'INSUFFICIENT_STOCK'); subtotal += gross; discountTotal += discount; taxTotal += lineTax; return { ...item, product, price, discount, net, lineTax, total: net + lineTax }; });
  const grandTotal = subtotal-discountTotal+taxTotal; const paymentTotal = input.payments.reduce((total,payment) => total + toPaise(payment.amount),0n); if (paymentTotal > grandTotal) throw new AppError(422, 'Payments cannot exceed the invoice total. Use the refund workflow for excess amounts.', 'OVERPAYMENT');
  const amountDue = grandTotal-paymentTotal; const paymentStatus = paymentTotal === 0n ? 'UNPAID' : amountDue === 0n ? 'PAID' : 'PARTIALLY_PAID';
  const year = new Date().getUTCFullYear(); await db.query(`INSERT INTO document_sequences(document_type,year,last_value) VALUES('INVOICE',$1,0) ON CONFLICT DO NOTHING`,[year]); const sequence = await db.query(`UPDATE document_sequences SET last_value=last_value+1 WHERE document_type='INVOICE' AND year=$1 RETURNING last_value`, [year]); const invoiceNumber = `INV-${year}-${String(sequence.rows[0].last_value).padStart(6,'0')}`;
  const invoice = await db.query(`INSERT INTO invoices(invoice_number,customer_id,payment_status,subtotal,discount_total,tax_total,grand_total,amount_paid,amount_due,cashier_id,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`, [invoiceNumber,input.customerId ?? null,paymentStatus,fromPaise(subtotal),fromPaise(discountTotal),fromPaise(taxTotal),fromPaise(grandTotal),fromPaise(paymentTotal),fromPaise(amountDue),actor.id,idempotencyKey]); const invoiceId = invoice.rows[0].id as string;
  for (const line of lines) { const description = [line.product.name,line.product.variant,line.product.color].filter(Boolean).join(' · '); await db.query(`INSERT INTO invoice_items(invoice_id,variant_id,sku_snapshot,description_snapshot,quantity,unit_price,discount_amount,tax_rate,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[invoiceId,line.variantId,line.product.sku,description,line.quantity,fromPaise(line.price),fromPaise(line.discount),line.product.tax_rate,fromPaise(line.total)]); const before = quantities.get(line.variantId)!; const after = before-line.quantity; await db.query('UPDATE inventory_balances SET quantity=$1,updated_at=now() WHERE variant_id=$2 AND location_id=$3',[after,line.variantId,input.locationId]); await db.query(`INSERT INTO inventory_movements(variant_id,location_id,movement_type,quantity_delta,quantity_before,quantity_after,reference_type,reference_id,performed_by) VALUES($1,$2,'SALE',$3,$4,$5,'INVOICE',$6,$7)`,[line.variantId,input.locationId,-line.quantity,before,after,invoiceId,actor.id]); }
  for (const payment of input.payments) await db.query(`INSERT INTO payments(invoice_id,amount,method,reference,received_by) VALUES($1,$2,$3,$4,$5)`,[invoiceId,payment.amount,payment.method,payment.reference ?? null,actor.id]);
  const response: Reply = { invoiceId, invoiceNumber, grandTotal: fromPaise(grandTotal), amountPaid: fromPaise(paymentTotal), amountDue: fromPaise(amountDue), paymentStatus };
  await audit(db,actor,{ action:'INVOICE_POSTED',entityType:'invoice',entityId:invoiceId,newValue:{...response,items:lines.map(l=>({variantId:l.variantId,quantity:l.quantity}))},transactionId:invoiceId,ip:context.ip,requestId:context.requestId });
  await db.query(`UPDATE idempotency_keys SET status_code=201,response_body=$2,completed_at=now() WHERE key=$1`,[idempotencyKey,response]); return response;
}
